version: '3.8'

services:
  chatbot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: memory-chatbot-dev
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /workspace

  chatbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memory-chatbot-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
